[package]
name = "cdup_rs_backend"
version = "0.1.0"
authors = ["kkew3 <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
regex = "1.5.4"
